language: python
python:
- '2.7'
node_js:
- "8.9.4"
install:
  - npm install
  - sudo pip install -r requirements.txt
script:
  - ./node_modules/.bin/dato dump
  - mkdocs build
  - git config --global user.email "dbreuer83@gmail.com"
  - git config --global user.name "David Breuer"
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: site
 on:
   branch: master
notifications:
  webhooks:
  - https://webhooks.datocms.com/d3f26f66eb45b610786d/deploy-results